using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]

public partial class MovModel

{
    [RealtimeProperty(1, true, true)]
    bool _movPlay;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class MovModel : RealtimeModel {
    public bool movPlay {
        get {
            return _movPlayProperty.value;
        }
        set {
            if (_movPlayProperty.value == value) return;
            _movPlayProperty.value = value;
            InvalidateReliableLength();
            FireMovPlayDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(MovModel model, T value);
    public event PropertyChangedHandler<bool> movPlayDidChange;
    
    public enum PropertyID : uint {
        MovPlay = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _movPlayProperty;
    
    #endregion
    
    public MovModel() : base(null) {
        _movPlayProperty = new ReliableProperty<bool>(1, _movPlay);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _movPlayProperty.UnsubscribeCallback();
    }
    
    private void FireMovPlayDidChange(bool value) {
        try {
            movPlayDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _movPlayProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _movPlayProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.MovPlay: {
                    changed = _movPlayProperty.Read(stream, context);
                    if (changed) FireMovPlayDidChange(movPlay);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _movPlay = movPlay;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
