using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using Normal.Realtime;
using Normal.Realtime.Serialization;
[RealtimeModel]
public partial class PianoModel
{
    [RealtimeProperty(1,true,true)]
    private string _note;

    [RealtimeProperty(2, true, true)]
    private bool _trigger;

    [RealtimeProperty(3, true, true)]
    private int _hit;
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class PianoModel : RealtimeModel {
    public string note {
        get {
            return _cache.LookForValueInCache(_note, entry => entry.noteSet, entry => entry.note);
        }
        set {
            if (this.note == value) return;
            _cache.UpdateLocalCache(entry => { entry.noteSet = true; entry.note = value; return entry; });
            InvalidateReliableLength();
            FireNoteDidChange(value);
        }
    }
    
    public bool trigger {
        get {
            return _cache.LookForValueInCache(_trigger, entry => entry.triggerSet, entry => entry.trigger);
        }
        set {
            if (this.trigger == value) return;
            _cache.UpdateLocalCache(entry => { entry.triggerSet = true; entry.trigger = value; return entry; });
            InvalidateReliableLength();
            FireTriggerDidChange(value);
        }
    }
    
    public int hit {
        get {
            return _cache.LookForValueInCache(_hit, entry => entry.hitSet, entry => entry.hit);
        }
        set {
            if (this.hit == value) return;
            _cache.UpdateLocalCache(entry => { entry.hitSet = true; entry.hit = value; return entry; });
            InvalidateReliableLength();
            FireHitDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PianoModel model, T value);
    public event PropertyChangedHandler<string> noteDidChange;
    public event PropertyChangedHandler<bool> triggerDidChange;
    public event PropertyChangedHandler<int> hitDidChange;
    
    private struct LocalCacheEntry {
        public bool noteSet;
        public string note;
        public bool triggerSet;
        public bool trigger;
        public bool hitSet;
        public int hit;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Note = 1,
        Trigger = 2,
        Hit = 3,
    }
    
    public PianoModel() : this(null) {
    }
    
    public PianoModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireNoteDidChange(string value) {
        try {
            noteDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireTriggerDidChange(bool value) {
        try {
            triggerDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireHitDidChange(int value) {
        try {
            hitDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteStringLength((uint)PropertyID.Note, _note);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Trigger, _trigger ? 1u : 0u);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Hit, (uint)_hit);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.noteSet) {
                length += WriteStream.WriteStringLength((uint)PropertyID.Note, entry.note);
            }
            if (entry.triggerSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Trigger, entry.trigger ? 1u : 0u);
            }
            if (entry.hitSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Hit, (uint)entry.hit);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteString((uint)PropertyID.Note, _note);
            stream.WriteVarint32((uint)PropertyID.Trigger, _trigger ? 1u : 0u);
            stream.WriteVarint32((uint)PropertyID.Hit, (uint)_hit);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.noteSet || entry.triggerSet || entry.hitSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.noteSet) {
                stream.WriteString((uint)PropertyID.Note, entry.note);
                didWriteProperties = true;
            }
            if (entry.triggerSet) {
                stream.WriteVarint32((uint)PropertyID.Trigger, entry.trigger ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.hitSet) {
                stream.WriteVarint32((uint)PropertyID.Hit, (uint)entry.hit);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Note: {
                    string previousValue = _note;
                    _note = stream.ReadString();
                    bool noteExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.noteSet);
                    if (!noteExistsInChangeCache && _note != previousValue) {
                        FireNoteDidChange(_note);
                    }
                    break;
                }
                case (uint)PropertyID.Trigger: {
                    bool previousValue = _trigger;
                    _trigger = (stream.ReadVarint32() != 0);
                    bool triggerExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.triggerSet);
                    if (!triggerExistsInChangeCache && _trigger != previousValue) {
                        FireTriggerDidChange(_trigger);
                    }
                    break;
                }
                case (uint)PropertyID.Hit: {
                    int previousValue = _hit;
                    _hit = (int)stream.ReadVarint32();
                    bool hitExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.hitSet);
                    if (!hitExistsInChangeCache && _hit != previousValue) {
                        FireHitDidChange(_hit);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _note = note;
        _trigger = trigger;
        _hit = hit;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
