using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;

using Normal.Realtime.Serialization;
[RealtimeModel]
public partial class EchoModel : RealtimeModel
{
    [RealtimeProperty(1, true, true)]
    private bool _echo;    
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class EchoModel : RealtimeModel {
    public bool echo {
        get {
            return _cache.LookForValueInCache(_echo, entry => entry.echoSet, entry => entry.echo);
        }
        set {
            if (this.echo == value) return;
            _cache.UpdateLocalCache(entry => { entry.echoSet = true; entry.echo = value; return entry; });
            InvalidateReliableLength();
            FireEchoDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(EchoModel model, T value);
    public event PropertyChangedHandler<bool> echoDidChange;
    
    private struct LocalCacheEntry {
        public bool echoSet;
        public bool echo;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Echo = 1,
    }
    
    public EchoModel() : this(null) {
    }
    
    public EchoModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireEchoDidChange(bool value) {
        try {
            echoDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Echo, _echo ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.echoSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Echo, entry.echo ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.Echo, _echo ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.echoSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.echoSet) {
                stream.WriteVarint32((uint)PropertyID.Echo, entry.echo ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Echo: {
                    bool previousValue = _echo;
                    _echo = (stream.ReadVarint32() != 0);
                    bool echoExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.echoSet);
                    if (!echoExistsInChangeCache && _echo != previousValue) {
                        FireEchoDidChange(_echo);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _echo = echo;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
