using System.Collections;
using System.Collections.Generic;
using Normal.Realtime;
using Normal.Realtime.Serialization;
using UnityEngine;

namespace C_scale
{
    [RealtimeModel]
    public partial class ScaleModel
    {
        [RealtimeProperty(1, true, true)] private float _gain;
        [RealtimeProperty(2, true, true)] private bool _echo;
    }

}

/* ----- Begin Normal Autogenerated Code ----- */
namespace C_scale {
    public partial class ScaleModel : RealtimeModel {
        public float gain {
            get {
                return _gainProperty.value;
            }
            set {
                if (_gainProperty.value == value) return;
                _gainProperty.value = value;
                InvalidateReliableLength();
                FireGainDidChange(value);
            }
        }
        
        public bool echo {
            get {
                return _echoProperty.value;
            }
            set {
                if (_echoProperty.value == value) return;
                _echoProperty.value = value;
                InvalidateReliableLength();
                FireEchoDidChange(value);
            }
        }
        
        public delegate void PropertyChangedHandler<in T>(ScaleModel model, T value);
        public event PropertyChangedHandler<float> gainDidChange;
        public event PropertyChangedHandler<bool> echoDidChange;
        
        public enum PropertyID : uint {
            Gain = 1,
            Echo = 2,
        }
        
        #region Properties
        
        private ReliableProperty<float> _gainProperty;
        
        private ReliableProperty<bool> _echoProperty;
        
        #endregion
        
        public ScaleModel() : base(null) {
            _gainProperty = new ReliableProperty<float>(1, _gain);
            _echoProperty = new ReliableProperty<bool>(2, _echo);
        }
        
        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
            _gainProperty.UnsubscribeCallback();
            _echoProperty.UnsubscribeCallback();
        }
        
        private void FireGainDidChange(float value) {
            try {
                gainDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        private void FireEchoDidChange(bool value) {
            try {
                echoDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        protected override int WriteLength(StreamContext context) {
            var length = 0;
            length += _gainProperty.WriteLength(context);
            length += _echoProperty.WriteLength(context);
            return length;
        }
        
        protected override void Write(WriteStream stream, StreamContext context) {
            var writes = false;
            writes |= _gainProperty.Write(stream, context);
            writes |= _echoProperty.Write(stream, context);
            if (writes) InvalidateContextLength(context);
        }
        
        protected override void Read(ReadStream stream, StreamContext context) {
            var anyPropertiesChanged = false;
            while (stream.ReadNextPropertyID(out uint propertyID)) {
                var changed = false;
                switch (propertyID) {
                    case (uint) PropertyID.Gain: {
                        changed = _gainProperty.Read(stream, context);
                        if (changed) FireGainDidChange(gain);
                        break;
                    }
                    case (uint) PropertyID.Echo: {
                        changed = _echoProperty.Read(stream, context);
                        if (changed) FireEchoDidChange(echo);
                        break;
                    }
                    default: {
                        stream.SkipProperty();
                        break;
                    }
                }
                anyPropertiesChanged |= changed;
            }
            if (anyPropertiesChanged) {
                UpdateBackingFields();
            }
        }
        
        private void UpdateBackingFields() {
            _gain = gain;
            _echo = echo;
        }
        
    }
}
/* ----- End Normal Autogenerated Code ----- */
