using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class SoundSyncModel
{   
    [RealtimeProperty(1,true,true)]
    private double _frequency;

    [RealtimeProperty(2,true,true)]
    private float _gain;


}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class SoundSyncModel : RealtimeModel {
    public double frequency {
        get {
            return _cache.LookForValueInCache(_frequency, entry => entry.frequencySet, entry => entry.frequency);
        }
        set {
            if (this.frequency == value) return;
            _cache.UpdateLocalCache(entry => { entry.frequencySet = true; entry.frequency = value; return entry; });
            InvalidateReliableLength();
            FireFrequencyDidChange(value);
        }
    }
    
    public float gain {
        get {
            return _cache.LookForValueInCache(_gain, entry => entry.gainSet, entry => entry.gain);
        }
        set {
            if (this.gain == value) return;
            _cache.UpdateLocalCache(entry => { entry.gainSet = true; entry.gain = value; return entry; });
            InvalidateReliableLength();
            FireGainDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(SoundSyncModel model, T value);
    public event PropertyChangedHandler<double> frequencyDidChange;
    public event PropertyChangedHandler<float> gainDidChange;
    
    private struct LocalCacheEntry {
        public bool frequencySet;
        public double frequency;
        public bool gainSet;
        public float gain;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Frequency = 1,
        Gain = 2,
    }
    
    public SoundSyncModel() : this(null) {
    }
    
    public SoundSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireFrequencyDidChange(double value) {
        try {
            frequencyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireGainDidChange(float value) {
        try {
            gainDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteDoubleLength((uint)PropertyID.Frequency);
            length += WriteStream.WriteFloatLength((uint)PropertyID.Gain);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.frequencySet) {
                length += WriteStream.WriteDoubleLength((uint)PropertyID.Frequency);
            }
            if (entry.gainSet) {
                length += WriteStream.WriteFloatLength((uint)PropertyID.Gain);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteDouble((uint)PropertyID.Frequency, _frequency);
            stream.WriteFloat((uint)PropertyID.Gain, _gain);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.frequencySet || entry.gainSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.frequencySet) {
                stream.WriteDouble((uint)PropertyID.Frequency, entry.frequency);
                didWriteProperties = true;
            }
            if (entry.gainSet) {
                stream.WriteFloat((uint)PropertyID.Gain, entry.gain);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Frequency: {
                    double previousValue = _frequency;
                    _frequency = stream.ReadDouble();
                    bool frequencyExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.frequencySet);
                    if (!frequencyExistsInChangeCache && _frequency != previousValue) {
                        FireFrequencyDidChange(_frequency);
                    }
                    break;
                }
                case (uint)PropertyID.Gain: {
                    float previousValue = _gain;
                    _gain = stream.ReadFloat();
                    bool gainExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.gainSet);
                    if (!gainExistsInChangeCache && _gain != previousValue) {
                        FireGainDidChange(_gain);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _frequency = frequency;
        _gain = gain;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
