using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class pianoLoopModel
{
    [RealtimeProperty(1, true, true)] private bool _pianoPlay;

    [RealtimeProperty(2, true, true)] private Color _color;
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class pianoLoopModel : RealtimeModel {
    public bool pianoPlay {
        get {
            return _pianoPlayProperty.value;
        }
        set {
            if (_pianoPlayProperty.value == value) return;
            _pianoPlayProperty.value = value;
            InvalidateReliableLength();
            FirePianoPlayDidChange(value);
        }
    }
    
    public UnityEngine.Color color {
        get {
            return _colorProperty.value;
        }
        set {
            if (_colorProperty.value == value) return;
            _colorProperty.value = value;
            InvalidateReliableLength();
            FireColorDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(pianoLoopModel model, T value);
    public event PropertyChangedHandler<bool> pianoPlayDidChange;
    public event PropertyChangedHandler<UnityEngine.Color> colorDidChange;
    
    public enum PropertyID : uint {
        PianoPlay = 1,
        Color = 2,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _pianoPlayProperty;
    
    private ReliableProperty<UnityEngine.Color> _colorProperty;
    
    #endregion
    
    public pianoLoopModel() : base(null) {
        _pianoPlayProperty = new ReliableProperty<bool>(1, _pianoPlay);
        _colorProperty = new ReliableProperty<UnityEngine.Color>(2, _color);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _pianoPlayProperty.UnsubscribeCallback();
        _colorProperty.UnsubscribeCallback();
    }
    
    private void FirePianoPlayDidChange(bool value) {
        try {
            pianoPlayDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireColorDidChange(UnityEngine.Color value) {
        try {
            colorDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _pianoPlayProperty.WriteLength(context);
        length += _colorProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _pianoPlayProperty.Write(stream, context);
        writes |= _colorProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.PianoPlay: {
                    changed = _pianoPlayProperty.Read(stream, context);
                    if (changed) FirePianoPlayDidChange(pianoPlay);
                    break;
                }
                case (uint) PropertyID.Color: {
                    changed = _colorProperty.Read(stream, context);
                    if (changed) FireColorDidChange(color);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _pianoPlay = pianoPlay;
        _color = color;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
