using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TestSyncModel
{
    [RealtimeProperty(1,true,true)]
    private Color _color;

    [RealtimeProperty(2,true,true)]
    private bool _isTouched;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TestSyncModel : RealtimeModel {
    public UnityEngine.Color color {
        get {
            return _cache.LookForValueInCache(_color, entry => entry.colorSet, entry => entry.color);
        }
        set {
            if (this.color == value) return;
            _cache.UpdateLocalCache(entry => { entry.colorSet = true; entry.color = value; return entry; });
            InvalidateReliableLength();
            FireColorDidChange(value);
        }
    }
    
    public bool isTouched {
        get {
            return _cache.LookForValueInCache(_isTouched, entry => entry.isTouchedSet, entry => entry.isTouched);
        }
        set {
            if (this.isTouched == value) return;
            _cache.UpdateLocalCache(entry => { entry.isTouchedSet = true; entry.isTouched = value; return entry; });
            InvalidateReliableLength();
            FireIsTouchedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TestSyncModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Color> colorDidChange;
    public event PropertyChangedHandler<bool> isTouchedDidChange;
    
    private struct LocalCacheEntry {
        public bool colorSet;
        public UnityEngine.Color color;
        public bool isTouchedSet;
        public bool isTouched;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Color = 1,
        IsTouched = 2,
    }
    
    public TestSyncModel() : this(null) {
    }
    
    public TestSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireColorDidChange(UnityEngine.Color value) {
        try {
            colorDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireIsTouchedDidChange(bool value) {
        try {
            isTouchedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
            length += WriteStream.WriteVarint32Length((uint)PropertyID.IsTouched, _isTouched ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.colorSet) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
            }
            if (entry.isTouchedSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.IsTouched, entry.isTouched ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(_color));
            stream.WriteVarint32((uint)PropertyID.IsTouched, _isTouched ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.colorSet || entry.isTouchedSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.colorSet) {
                stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(entry.color));
                didWriteProperties = true;
            }
            if (entry.isTouchedSet) {
                stream.WriteVarint32((uint)PropertyID.IsTouched, entry.isTouched ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Color: {
                    UnityEngine.Color previousValue = _color;
                    _color = ReadStream.ColorFromBytes(stream.ReadBytes());
                    bool colorExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.colorSet);
                    if (!colorExistsInChangeCache && _color != previousValue) {
                        FireColorDidChange(_color);
                    }
                    break;
                }
                case (uint)PropertyID.IsTouched: {
                    bool previousValue = _isTouched;
                    _isTouched = (stream.ReadVarint32() != 0);
                    bool isTouchedExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.isTouchedSet);
                    if (!isTouchedExistsInChangeCache && _isTouched != previousValue) {
                        FireIsTouchedDidChange(_isTouched);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _color = color;
        _isTouched = isTouched;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
