using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;

using Normal.Realtime.Serialization;
[RealtimeModel]
public partial class beatModel {
    [RealtimeProperty(1, true, true)]
    private Color _color;
    [RealtimeProperty(2, true, true)]
    private bool _play;
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class beatModel : RealtimeModel {
    public UnityEngine.Color color {
        get {
            return _cache.LookForValueInCache(_color, entry => entry.colorSet, entry => entry.color);
        }
        set {
            if (this.color == value) return;
            _cache.UpdateLocalCache(entry => { entry.colorSet = true; entry.color = value; return entry; });
            InvalidateReliableLength();
            FireColorDidChange(value);
        }
    }
    
    public bool play {
        get {
            return _cache.LookForValueInCache(_play, entry => entry.playSet, entry => entry.play);
        }
        set {
            if (this.play == value) return;
            _cache.UpdateLocalCache(entry => { entry.playSet = true; entry.play = value; return entry; });
            InvalidateReliableLength();
            FirePlayDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(beatModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Color> colorDidChange;
    public event PropertyChangedHandler<bool> playDidChange;
    
    private struct LocalCacheEntry {
        public bool colorSet;
        public UnityEngine.Color color;
        public bool playSet;
        public bool play;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Color = 1,
        Play = 2,
    }
    
    public beatModel() : this(null) {
    }
    
    public beatModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireColorDidChange(UnityEngine.Color value) {
        try {
            colorDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FirePlayDidChange(bool value) {
        try {
            playDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Play, _play ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.colorSet) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
            }
            if (entry.playSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Play, entry.play ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(_color));
            stream.WriteVarint32((uint)PropertyID.Play, _play ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.colorSet || entry.playSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.colorSet) {
                stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(entry.color));
                didWriteProperties = true;
            }
            if (entry.playSet) {
                stream.WriteVarint32((uint)PropertyID.Play, entry.play ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Color: {
                    UnityEngine.Color previousValue = _color;
                    _color = ReadStream.ColorFromBytes(stream.ReadBytes());
                    bool colorExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.colorSet);
                    if (!colorExistsInChangeCache && _color != previousValue) {
                        FireColorDidChange(_color);
                    }
                    break;
                }
                case (uint)PropertyID.Play: {
                    bool previousValue = _play;
                    _play = (stream.ReadVarint32() != 0);
                    bool playExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.playSet);
                    if (!playExistsInChangeCache && _play != previousValue) {
                        FirePlayDidChange(_play);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _color = color;
        _play = play;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
