using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TestSyncModel
{
    [RealtimeProperty(1, true, true)] private Color _color;

    [RealtimeProperty(2, true, true)] private bool _isTouched;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TestSyncModel : RealtimeModel {
    public UnityEngine.Color color {
        get {
            return _colorProperty.value;
        }
        set {
            if (_colorProperty.value == value) return;
            _colorProperty.value = value;
            InvalidateReliableLength();
            FireColorDidChange(value);
        }
    }
    
    public bool isTouched {
        get {
            return _isTouchedProperty.value;
        }
        set {
            if (_isTouchedProperty.value == value) return;
            _isTouchedProperty.value = value;
            InvalidateReliableLength();
            FireIsTouchedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TestSyncModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Color> colorDidChange;
    public event PropertyChangedHandler<bool> isTouchedDidChange;
    
    public enum PropertyID : uint {
        Color = 1,
        IsTouched = 2,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Color> _colorProperty;
    
    private ReliableProperty<bool> _isTouchedProperty;
    
    #endregion
    
    public TestSyncModel() : base(null) {
        _colorProperty = new ReliableProperty<UnityEngine.Color>(1, _color);
        _isTouchedProperty = new ReliableProperty<bool>(2, _isTouched);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _colorProperty.UnsubscribeCallback();
        _isTouchedProperty.UnsubscribeCallback();
    }
    
    private void FireColorDidChange(UnityEngine.Color value) {
        try {
            colorDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireIsTouchedDidChange(bool value) {
        try {
            isTouchedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _colorProperty.WriteLength(context);
        length += _isTouchedProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _colorProperty.Write(stream, context);
        writes |= _isTouchedProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Color: {
                    changed = _colorProperty.Read(stream, context);
                    if (changed) FireColorDidChange(color);
                    break;
                }
                case (uint) PropertyID.IsTouched: {
                    changed = _isTouchedProperty.Read(stream, context);
                    if (changed) FireIsTouchedDidChange(isTouched);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _color = color;
        _isTouched = isTouched;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
